### ISSUE TITLE
All services become unreachabe after install

### ISSUE THREAD

**Issue by zimbres** [newsnowlabs/docker-ingress-routing-daemon#14] opened 2021-09-05 13:39 UTC
Hello,

Tried to use this script, but after install it all services present on swarm become unreachable, If i specify a service on install process only this one become reachable. Manual container are not affected. Once uninstalled all back to work.

DIRD 3.3.0
Machines are Ubuntu 20.04

What else information is useful to help identify this behavior?

**Comment by struanb** [comment] 2021-09-05 14:16
Hi @zimbres thank you for trying DIND. I would need more information, ideally sufficient to reproduce the problem on my own systems. I realise that's difficult when you may be running bespoke applications though.

Still what would be useful is information about your docker swarm topology: how many nodes, how many are used as are load balancers, the load balancers ingress network IPs, the names of the services you're running and the ports and protocols being exposed by each of those services (listed separately), the DIND command line you're running (which should reflect all of the above), confirmation you're running DIND on all nodes, and that you've shutdown and relaunched (or scaled to zero and back) the services selected to be affected by DIND.

That should help get the investigation underway, and we'll take it from there.

**Comment by zimbres** [comment] 2021-09-05 19:28
Hi, missing was scale down to zero the service after installation! Tks

I realized that I need to set services and ports at installation, otherwise all ports of all services are affected and not only the informed service.

For the records, in my case even with a machine with a /16 subnet on ingress, its working. I have only one service exposed that is an Kong API Gateway where I applied the DIND.

Whats is good strategy to run the script at machine boot? I tried rc.local but at the moment of its execution the ingress network is not available yet.

**Comment by struanb** [comment] 2021-09-05 20:34
Hi @zimbres. That's great news. Yes, for service containers that are already running _prior_ to running DIND, DIND will disable SNAT immediately (which will break routing) but not add the policy routing/firewall rules to the service containers, since it only does that for new service containers as they are launched.

It's good to hear DIND is working with a /16 subnet. But a word of warning: I _think_ it will be fine as long as the nodes you are using as load balancers all have a different final byte in their /16 IP address - but otherwise I would expect it to break!

So, for example, if your load balancer nodes are x.y.10.2, x.y.11.3 and x.y.12.4, then the TOS byte, which will be set to 2, 3 or 4, can uniquely identify and represent the load balancer in the container firewall and routing rules. But if one load balancer node was x.y.13.4 then it would clash with x.y.12.4 - both nodes would set the TOS byte to 4, and the containers would set up conflicting and broken firewall and routing rules.

(Thinking this through, I can imagine a workaround to make this safe: instead of using the final byte of the load balancer ingress IP for the TOS byte, instead order the load balancer IPs and for the TOS byte use their index (numbered 1...n where n is the number of load balancer nodes). These TOS bytes will be unique for each load balancer node and still allow operation with ingress networks larger than /24: /16 or even /8. Perhaps I will add this functionality later!)

**Comment by struanb** [comment] 2021-09-05 20:36
To run the script at boot, we use something like this systemd unit, installed at `/etc/systemd/system/dind.service`:

```
[Unit]
Description=Docker Ingress Routing Daemon
After=sysinit.target dockerd.service
StartLimitIntervalSec=0

[Service]
ExecStart=/usr/local/bin/docker-ingress-routing-daemon --ingress-gateway-ips 10.0.0.2 --install
Restart=always

[Install]
WantedBy=multi-user.target
```

N.B. Obviously it's necessary to customise the `ExecStart` option according to your requirements.

**Comment by struanb** [comment] 2021-09-05 23:07
> (Thinking this through, I can imagine a workaround to make this safe: instead of using the final byte of the load balancer ingress IP for the TOS byte, instead order the load balancer IPs and for the TOS byte use their index (numbered 1...n where n is the number of load balancer nodes). These TOS bytes will be unique for each load balancer node and still allow operation with ingress networks larger than /24: /16 or even /8. Perhaps I will add this functionality later!)

FYI I've implemented this workaround so as to provide full support for /16 ingress networks, and hope to push to a branch soon. If you can test, that would be fantastic. Details will be posted to https://github.com/newsnowlabs/docker-ingress-routing-daemon/issues/15.

**Comment by zimbres** [comment] 2021-09-06 17:17
Hi, o got the point of subnet size, In my case I have just one node under validations to be implemented. So, its not a problem at all.

I chose a /16 subnet after face problem at ingress network with some containers that is in a failing loop and this exhausted the network IP delivery. After some research looks like also Docker advise to use bigger subnets.

I appreciate the systemctl script, works fine.

For sure I can test the version of /16 networks that  you change, but since I running only one node, not sure if will produce the expect results, let me know.

**Comment by struanb** [comment] 2021-09-06 20:14
HI @zimbres. You're right! With only one load balancer, there is no risk at all in using DIND v3.3.0 (as long as it doesn't have a `.0` ingress IP address!) and my DIND v4.0.0 code would add little value (except it would work with a `.0` ingress IP address).

Still, if you have a moment, please check out and test the https://github.com/newsnowlabs/docker-ingress-routing-daemon/tree/indexeds-ids branch, and add any comments on #15 (at least, I hope it will give you clearer logging of DIND's activities).

As we've dealt with your original issue, I will close this issue now.

**Closed by struanb** 2021-09-06 20:14 UTC
